### PR TITLE
[DataGrid] Initial Selection

### PR DESCRIPTION
**Pull request by Domino987**
Adding initial row and checkbox selection to the data-grid.

### CODE REVIEW

**Comment by oliviertassinari** [comment]
Note that @gabrielliwerant had plans to look into the selection feature.

**Comment by Domino987** [comment]
I see, where did he say? He can of course join me for the selection.

**Comment by Domino987** [comment]
@gabrielliwerant @oliviertassinari What do you think my approach? Could you review it?

**Comment by oliviertassinari** [comment]
@Domino987 Yes, I will give it a look by the end of the day :)

**Comment by oliviertassinari** [comment]
@Domino987 Hi, thanks for waiting. @dtassone will be leading the date grid effort. We will let you know once we can accept help :).

**Pull request closed without merging**
